builders:
  state_extension:
    import: "package:state_extension/builder.dart"
    builder_factories: ["stateExtension"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]