builders:
  bloc_state_gen:
    import: "package:bloc_state_gen/builder.dart"
    builder_factories: ["stateExtension"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]