targets:
  $default:
    builders:
      bloc_state_gen:
        enabled: true

builders:
  bloc_state_gen:
    import: "package:bloc_state_gen/bloc_state_gen_builder.dart"
    builder_factories: [ "blocStateGenBuilder" ]
    build_extensions: { ".dart": [ ".s.dart" ] }
    auto_apply: dependents
    build_to: source