name: bloc_state_gen
description: "Generate helper extensions for Bloc and Cubit states with type-safe pattern matching and logging."
version: 1.1.0
homepage: https://github.com/azharbinanwar/bloc_state_gen

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.11.0
  build: ^2.4.2
  source_gen: ^2.0.0
  meta: 1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
