name: bloc_state_gen
description: "A package to generate helper extensions for Bloc state management, like when and maybeWhen."
version: 0.1.0+2
homepage: https://github.com/azharbinanwar/bloc_state_gen # Replace with your repository or homepage URL

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  source_gen: ^1.4.0
  meta: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.2.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
# Add assets or other configurations here if required
